doctrine:
    dbal:
#        default_connection: default
#        connections:
#            default:
#                dbname: '%env(resolve:MYSQL_DB)%'
#                host: '%env(resolve:MYSQL_HOST)%'
#                port: '%env(resolve:MYSQL_PORT)%'
#                user: '%env(resolve:MYSQL_USER)%'
#                password: '%env(resolve:MYSQL_PASSWORD)%'
#                driver: 'pdo_mysql'
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        default_entity_manager: default
#        auto_generate_proxy_classes: "%kernel.debug%"
#        entity_managers:
#            default:
#                connection: default
#                auto_mapping: true
#                mappings:
#                    App:
#                        is_bundle: false
#                        type: yml
#                        dir: '%kernel.project_dir%/config/doctrine/model'
#                        prefix: 'App\Entity'
#                        alias: App
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
