#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number

main:
  path: /
  controller: App\Controller\MainController::main

basket.post:
  path: /basket
  controller: App\Controller\BasketController::add
  methods: [POST]

petId.post:
  path: /pet/{petId}
  controller: App\Controller\BasketController::add
  methods: [POST]

flowerCategoryId:
  path: /editCategory/{categoryId}
  controller: App\Controller\FlowerCategoryController::edit
  methods: [GET, POST]

flowerCategorySave:
  path: /saveCategory
  controller: App\Controller\FlowerCategoryController::save
  methods: [POST]

_swagger-ui:
  resource: '@HBSwaggerUiBundle/Resources/config/routing.yml'
  prefix: /docs

sonata_user_admin_security:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /admin

sonata_user_admin_resetting:
  resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
  prefix: /admin/resetting