swagger: "2.0"

info:
  title: Flowers API
  description: Products API of Flowers
  version: 1.0.0

servers:
  - url: http://flower
    description: Localhost server from develop
  - url: http://dostavka-buketov.ru
    description: Prod server

tags:
  - name: Bouquets
    description: ПBouquets

paths:
  /basket:
    post:
      tags:
        - "flo"
      summary: "test"
      description: "zzzzzzzzzzzzzzz"
      operationId: "put to basket"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - name: "flowerId"
          in: "formData"
          description: "Additional data to pass to server"
          required: true
          type: "integer"
        - name: "flowerName"
          in: "formData"
          description: "Name flower"
          required: true
          type: "string"
      responses:
        200:
          description: "successful operation"
  #          schema:
  #            $ref: "#/definitions/ApiResponse"
  # Корзина
  /basket0:
    post:
      tags:
        - Bouquets
      summary: Запрос КБМ
      description: >
        Метод возвращает КБМ одного или нескольких водителей
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                drivers:
                  type: array
                  items:
                    type: number
                    description: КБМ
                    example: 0.8
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  kbm:
                    type: number
                    description: КБМ
                    example: 0.8
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        kbm:
                          type: number
                          description: КБМ
                          example: 0.8
        404:
          $ref: '#/components/schemas/404'


components:
  schemas:
    404:
      description: Not found response
      type: string
      example: Not found