openapi: 3.0.0

info:
  title: Flowers API
  description: Products API of Flowers
  version: 1.0.0

servers:
  - url: http://flower
    description: Localhost server from develop

tags:
  - name: Bouquets
    description: Продукт ОСАГО

paths:
  # osago
  /product/osago/get-kbm:
    post:
      tags:
        - Bouquets
      summary: Запрос КБМ
      description: >
        Метод возвращает КБМ одного или нескольких водителей
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                drivers:
                  type: array
                  items:
                    type: number
                    description: КБМ
                    example: 0.8
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  kbm:
                    type: number
                    description: КБМ
                    example: 0.8
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        kbm:
                          type: number
                          description: КБМ
                          example: 0.8
        404:
          $ref: '#/components/schemas/404'


components:
  schemas:
    404:
      description: Not found response
      type: string
      example: Not found