<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLyshO4g\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLyshO4g/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLyshO4g.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLyshO4g\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLyshO4g\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LyshO4g',
    'container.build_id' => 'cadea879',
    'container.build_time' => 1623856215,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLyshO4g');
