openapi: 3.0.0

info:
  title: Flowers
  description: Flowers api
  version: 1.0.0

servers:
  - url: http://flower
    description: Localhost server from develop

tags:
  - name: ОСАГО
    description: Продукт ОСАГО
  - name: КАСКО
    description: Продукт КАСКО
  - name: ИФЛ
    description: Продукт ИФЛ (недвижимость)
  - name: ВЗР
    description: Продукт ВЗР (путешествия)

paths:
# osago
  /basket:
    post:
      tags:
        - ОСАГО
      summary: Запрос КБМ
      description: >
        Метод возвращает КБМ одного или нескольких водителей
      requestBody:
        content:
          application/json:
            schema:
              type: object
                properties:
                  status:
                    type: string
                    description: Статус запроса
                    example: processing
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  kbm:
                    type: number
                    description: КБМ
                    example: 0.8
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        kbm:
                          type: number
                          description: КБМ
                          example: 0.8

